import type { Locale } from "./i18n";

export const experienceMessages: Record<Locale, {
  findTitle: string; findBody: string; need: string; where: string; payment: string;
  any: string; self: string; insurance: string; submit: string; close: string;
  popular: string; fullSearch: string; askBody: string; fullAsk: string; providerOne: string; providerMany: string; seeAll: string;
}> = {
  en: { findTitle: "Find a healthcare price", findBody: "Search published prices from verified providers.", need: "What are you looking for?", where: "Where?", payment: "How are you paying?", any: "Any payment", self: "Self-pay / no insurance", insurance: "Published insurance rates", submit: "Search prices", close: "Close", popular: "Popular searches", fullSearch: "Open full search", askBody: "Find providers, procedures, and published healthcare prices.", fullAsk: "Open full Ask Carevero", providerOne: "1 provider with published prices", providerMany: "{count} providers with published prices", seeAll: "See all {count} providers" },
  es: { findTitle: "Buscar un precio de atención médica", findBody: "Busque precios publicados por proveedores verificados.", need: "¿Qué está buscando?", where: "¿Dónde?", payment: "¿Cómo pagará?", any: "Cualquier forma de pago", self: "Pago directo / sin seguro", insurance: "Tarifas de seguro publicadas", submit: "Buscar precios", close: "Cerrar", popular: "Búsquedas populares", fullSearch: "Abrir búsqueda completa", askBody: "Encuentre proveedores, procedimientos y precios publicados.", fullAsk: "Abrir Preguntar a Carevero", providerOne: "1 proveedor con precios publicados", providerMany: "{count} proveedores con precios publicados", seeAll: "Ver los {count} proveedores" },
  vi: { findTitle: "Tìm giá dịch vụ y tế", findBody: "Tìm giá công bố từ các nhà cung cấp đã xác minh.", need: "Bạn đang tìm gì?", where: "Ở đâu?", payment: "Bạn thanh toán thế nào?", any: "Mọi hình thức", self: "Tự thanh toán / không bảo hiểm", insurance: "Giá bảo hiểm đã công bố", submit: "Tìm giá", close: "Đóng", popular: "Tìm kiếm phổ biến", fullSearch: "Mở trang tìm kiếm", askBody: "Tìm nhà cung cấp, thủ thuật và giá y tế đã công bố.", fullAsk: "Mở Hỏi Carevero", providerOne: "1 nhà cung cấp có giá công bố", providerMany: "{count} nhà cung cấp có giá công bố", seeAll: "Xem tất cả {count} nhà cung cấp" },
  "zh-TW": { findTitle: "尋找醫療價格", findBody: "搜尋經驗證提供者的已公布價格。", need: "您在找什麼？", where: "地點？", payment: "您如何付款？", any: "任何付款方式", self: "自費／無保險", insurance: "已公布保險費率", submit: "搜尋價格", close: "關閉", popular: "熱門搜尋", fullSearch: "開啟完整搜尋", askBody: "尋找提供者、醫療項目與已公布價格。", fullAsk: "開啟詢問 Carevero", providerOne: "1 個提供者有已公布價格", providerMany: "{count} 個提供者有已公布價格", seeAll: "查看全部 {count} 個提供者" },
  "zh-CN": { findTitle: "查找医疗价格", findBody: "搜索经验证提供者的已公布价格。", need: "您在找什么？", where: "地点？", payment: "您如何付款？", any: "任何付款方式", self: "自费／无保险", insurance: "已公布保险费率", submit: "搜索价格", close: "关闭", popular: "热门搜索", fullSearch: "打开完整搜索", askBody: "查找提供者、医疗项目和已公布价格。", fullAsk: "打开询问 Carevero", providerOne: "1 个提供者有已公布价格", providerMany: "{count} 个提供者有已公布价格", seeAll: "查看全部 {count} 个提供者" },
};
